[package]
name = "local-forwarder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc.3"
color-eyre = "0.6.2"
tokio = { version = "1.29.1", features = ["full"] }
udp-stream = "0.0.9"
