[package]
name = "udp-server-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
tokio = { version = "1.30.0", features = ["full"] }
udp-stream = "0.0.9"
udpflow = "0.1.0"
