version: '3.8'
services:
  client:
    image: filipton/lf-client:latest
    restart: always
    network_mode: host
    environment:
      - LF_ENV=true
      - LF_CONNECTOR=localhost:1337
      - LF_CODE=694201337
      - LF_PORT1=localhost:8080:80/tcp
      - LF_PORT2=localhost:1234:80/tcp
    # You can also just mount the config file
    # volumes:
    #   - ./config.json:/app/config.json

    # Obviously server would be on another machine, but for simplicity its in the same file
  server:
    image: filipton/lf-server:latest
    restart: always
    network_mode: host
    # You can also expose docker ports
    # ports:
    #   - 8080:8080
    #   - 1234:8080

    environment:
      - LF_ENV=true
      - LF_PORT=1337
      - LF_CODE=694201337
    # You can also just mount the config file
    # volumes:
    #   - ./config.json:/etc/local-forwarder/config.json
    #
    #   Or you can mount whole /etc/local-forwarder dir
    #   - ./config:/etc/local-forwarder
